### ISSUE TITLE
GUI is messed up

### ISSUE THREAD

**Issue by robsalasco** [nodegui/svelte-nodegui-starter#4]
Hi!

I followed the getting started guide and when I run the app it looks very bad.

<img width="777" alt="Captura de Pantalla 2021-06-03 a la(s) 22 16 22" src="https://user-images.githubusercontent.com/2642107/120736443-3fe70d00-c4ba-11eb-8ebe-28a08a67e155.png">

**Comment by jsprog** [comment]
I'm facing the same problem when using custom components. direct content is not affected by this and should render right.

Note: Adding margin to some elements will cause their background to shrink.

**Comment by ceremcem** [comment]
Same on Debian Buster. Is anyone handling this problem?

**Comment by Levyks** [comment]
Same in Winows 11

**Comment by shirakaba** [comment]
Closed in favour of https://github.com/nodegui/svelte-nodegui/issues/72

**Comment by shayneoneill** [comment]
Was this ever resolved?

**Comment by jsprog** [comment]
@shayneoneill, This project is already abandoned and dead, It is archived by owner more than year ago.

You better lean rust programming language seriously then explore the good alternatives such as Tauri, Dioxus, Slint, etc...

**Comment by shayneoneill** [comment]
Oh I know my way around rust. Its just sad to see a really viable solution die. 

QT and C++ still rules my roost, alas.

**Comment by jsprog** [comment]
@shayneoneill, This repository isn't a serious project from the start. The momentum was huge at beginning but It cooled down too fast and the developer wasn't interested or wasn't having time for this.

Also, many libraries in the javascript ecosystem especially node.js utilities are now written using rust for efficiency and faster processing.

Don't use C++, the whole world is moving from nearly every programming language to Rust

**Comment by jsprog** [comment]
@shayneoneill, This was never a serious project from the start
